apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app
  labels:
    app: simple-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
        - name: simple-python-app
          image: sharanu363/simple-python-app30:latest
          ports:
            - containerPort: 5000
