apiVersion: v1
kind: Service
metadata:
  name: simple-python-app
spec:
  type: NodePort  # or LoadBalancer, depending on your environment
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: simple-python-app
